fix no file in path error
script broke on empty folder

Traceback (most recent call last):
  File "/home/OrganizeMediaFiles/src/organize_media_files.py", line 322, in <module>
    main()
  File "/home/OrganizeMediaFiles/src/organize_media_files.py", line 291, in main
    img_processed, img_removed, img_copied, img_skipped = organize_files(IMAGES_SOURCE_PATH,
  File "/home/OrganizeMediaFiles/src/organize_media_files.py", line 186, in organize_files
    _num_files_processed, _num_files_removed, _num_files_copied, _num_files_skipped = organize_files(
  File "/home/OrganizeMediaFiles/src/organize_media_files.py", line 186, in organize_files
    _num_files_processed, _num_files_removed, _num_files_copied, _num_files_skipped = organize_files(
  File "/home/OrganizeMediaFiles/src/organize_media_files.py", line 186, in organize_files
    _num_files_processed, _num_files_removed, _num_files_copied, _num_files_skipped = organize_files(
ValueError: not enough values to unpack (expected 4, got 3)